import { Inter } from "next/font/google";
import "./globals.css";

import { NavBar } from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Principal",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
